### PR TITLE
add proxy support with got and node-tunnel

### LINKED ISSUE #7: Proxy support
Hi, my service are running behind a firewall which require a proxy to access configure file. Node SDK seems not able to send request over proxy.

### PR DESCRIPTION
**Pull request by ziofat**
I replaced ky with got and using tunnel package to create an agent as proxy.
It should resolve #7

### CODE REVIEW

**Comment by configcat** [comment]
@ziofat
The build fails when runing `npm install` then `npm run build`. Can you check on your end? Am I missing something?

**Comment by ziofat** [comment]
Maybe you should check https://github.com/configcat/common-js/pull/3 first, as it introduces the `proxy` attribute in ClientOptions where this PR is relying on.

You should run `npm link` on common-js and then run `npm link configcat-common` in this PR. Then it should work.

**Comment by configcat** [comment]
I have tested, merged and released a new version.
Thank you very much for the contribution and the help!

**Comment by ziofat** [comment]
Great! I was worried about the SSR thing.

**Pull request merged**
